# Site settings
title: Vitality Future
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Vitality Future
user_description: Vitality Future Technology Co., Ltd. firmly believes that technology makes people's lives more convenient. Based on this concept, we focuses on developing practical tool apps. Currently, the products under development include accounting, turntable, countdown, and other apps. In the future, we will also provide more high-quality, high-quality mobile phone applications to a wide range of users.
user_title: Focus on developing fun and easy-to-use apps
email: vitalityfuture@126.com
# twitter_username: lorem_ipsum
instagram_username: mauriciourraco7
facebook_username: mauricio.urraco
linkedin_username: murraco
github_username:  VitalityFuture
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

